name: Linux

on: [push, pull_request]

jobs:
  # Building using the github runner environement directly.
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check cmake
      run: cmake --version
    - name: Swig install
      run: |
        wget "https://downloads.sourceforge.net/project/swig/swig/swig-4.0.1/swig-4.0.1.tar.gz";
        tar xvf swig-4.0.1.tar.gz;
        rm swig-4.0.1.tar.gz;
        cd swig-4.0.1;
        ./configure --prefix=/usr;
        make -j8;
        sudo make install;
        cd ..;
        rm -rf swig-4.0.1;
    - name: Check swig
      run: swig -version
    - name: Check dotnet
      run: dotnet --info
    - name: Configure
      run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build build --target all -v
    - name: Test
      run: cmake --build build --target test -v
    - name: Install
      run: cmake --build build --target install -v -- DESTDIR=install
